### ISSUE TITLE
Mensajes de Error al usar find_author_scopus_id_by_name

### ISSUE THREAD

**Issue by rfabila** [rfabila/Pyscholar#3]
Sería bueno que la función explicara que errores tuvo. Es decir que si llamo desde
una IP no válida se lo haga saber al usuario.

**Comment by aniale** [comment]
Ejemplo:
Poner un try except al codigo para que detecte los errores.
try:
   resp = request (...)
except:
   print "URL invalida"

**Comment by rfabila** [comment]
Sí eso estaría bien! Lanzar excepciones.
